apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-sync-webapp-deployment
spec:
  template:
    spec:
      containers:
        - name: config-sync-webapp
          image: nikhil575/config-sync-service:latest
