apiVersion: apps/v1
kind: Deployment
metadata:
  name: dept-webapp-deployment
spec:
  template:
    spec:
      containers:
        - name: dept-webapp
          image: nikhil575/departmentservice:latest
