apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service-deployment
  labels:
    app: auth-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - name: auth-service
          image: nikhil575/auth-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8050
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "default"
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service-service
spec:
  selector:
    app: auth-service
  ports:
    - port: 8055
      targetPort: 8055
