apiVersion: v1
kind: Namespace
metadata:
  name: couchbase

---
apiVersion: v1
kind: Service
metadata:
  name: couchbase-service
  namespace: couchbase
spec:
  ports:
    - name: couchbase-admin
      port: 8091
      targetPort: 8091
    - name: couchbase-api
      port: 8092
      targetPort: 8092
    - name: couchbase-views
      port: 8093
      targetPort: 8093
    - name: couchbase-query
      port: 8094
      targetPort: 8094
    - name: couchbase-sync
      port: 4984
      targetPort: 4984
  clusterIP: None
  selector:
    app: couchbase

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: couchbase-cluster
  namespace: couchbase
spec:
  serviceName: couchbase-service
  replicas: 1  # 🔸 Increase this to 3+ for production
  selector:
    matchLabels:
      app: couchbase
  template:
    metadata:
      labels:
        app: couchbase
    spec:
      containers:
        - name: couchbase
          image: couchbase:community-7.2.0
          ports:
            - containerPort: 8091
            - containerPort: 8092
            - containerPort: 8093
            - containerPort: 8094
          env:
            - name: COUCHBASE_ADMINISTRATOR_USERNAME
              value: "Administrator"
            - name: COUCHBASE_ADMINISTRATOR_PASSWORD
              value: "password"
          volumeMounts:
            - name: couchbase-data
              mountPath: /opt/couchbase/var
      terminationGracePeriodSeconds: 30
  volumeClaimTemplates:
    - metadata:
        name: couchbase-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
